[package]
name = "mazetool"
version = "0.1.0"
authors = [ "Markus Silv√°n <msilvan@iki.fi>" ]
readme = "README.md"
edition = "2018"

[dependencies]
getopts = "0.2"
log = "0.4"
simple_logger = "1.11"
rand = "0.8"

ggez = "0.6.1"
glam = "0.17.3"
winit = "0.25.0"

crossbeam = "0.8.1"
