[package]
name = "mazetool"
version = "0.2.0"
authors = [ "Markus Silv√°n <msilvan@iki.fi>" ]
readme = "README.md"
edition = "2021"

[dependencies]
log = "0.4"
simple_logger = "1.11"
rand = "0.8"
clap = "2.33"

ggez = "0.6.1"
glam = "0.17.3"
winit = "0.25.0"

crossbeam = "0.8.1"

heapless = "0.7.9"
